#!/bin/bash

echo Validating formatting
black --check .
if [ $? -ne 0 ]
then
  echo -e 'Formatting check failed. Run \033[1m\033[0;36m"black ."\033[0m'
  exit 1
fi

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"
