# Verify that the docs build correctly
name: Pull Request Docs Check

  on: [ pull_request ]

  jobs:
    build:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1
        - uses: ammaraskar/sphinx-action@master
          with:
            docs-folder: "docs/"
